version: '3'
services: 
    webserver: 
        image: webdevops/php-apache:7.3
        container_name: ${PROJECT_NAME}_webserver
        volumes: 
            - ./htdocs:/var/www/vhosts/${PROJECT_NAME}/htdocs
            - ./etc/apache2/sites-enabled:/etc/apache2/sites-enabled
            - ./logs:/var/log/apache2
        expose: 
            - 80
        ports: 
            - 80:80 
networks: 
    default: 
        external: 
            name: dev-network
